name: clubmark3
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  equatable: ^2.0.3
  blurrycontainer: ^0.0.1
  geolocator: ^7.7.1
  geocoding: ^2.0.1
  intro_slider: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/images/top.png
    - lib/assets/images/Ellipse 8.png
    - lib/assets/images/bluetick.png
    - lib/assets/images/bottombar.png
    - lib/assets/images/bottomleft.png
    - lib/assets/images/clubphoto.jpg
    - lib/assets/images/clubphoto2.jpg
    - lib/assets/images/couple.png
    - lib/assets/images/eliteclubfeatured.jpg
    - lib/assets/images/elitefeatured.jpg
    - lib/assets/images/event1.jpg
    - lib/assets/images/event2.jpg
    - lib/assets/images/event3.jpg
    - lib/assets/images/event4.jpg
    - lib/assets/images/event5.jpg
    - lib/assets/images/event6.jpg
    - lib/assets/images/facebookIcon.png
    - lib/assets/images/facebookIconPressed.png
    - lib/assets/images/googleIcon.png
    - lib/assets/images/guabafeatured.jpg
    - lib/assets/images/hello1.jpg
    - lib/assets/images/hello2.jpg
    - lib/assets/images/hello3.jpg
    - lib/assets/images/male.png
    - lib/assets/images/numba2.png
    - lib/assets/images/numba3.png
    - lib/assets/images/numba4.png
    - lib/assets/images/person.png
    - lib/assets/images/play.png
    - lib/assets/images/purplewatch.png
    - lib/assets/images/randomface.jpg
    - lib/assets/images/register.png
    - lib/assets/images/search.png
    - lib/assets/images/single.png
    - lib/assets/images/ticket.png
    - lib/assets/images/topbig.png
    - lib/assets/images/toptop.png
    - lib/assets/images/vibes.png
    - lib/assets/images/music_types/hiphop.jpg
    - lib/assets/images/music_types/jazz.jpg
    - lib/assets/images/music_types/livemusic.jpg
    - lib/assets/images/music_types/native.jpg
    - lib/assets/images/music_types/pop.jpg
    - lib/assets/images/music_types/reggae.jpg
    - lib/assets/images/music_types/rnb.jpg
    - lib/assets/images/music_types/rock.jpg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
